site:
  name: BGS İnteraktif A.Ş.
  site: 'https://bgs.io'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

metadata:
  title:
    default: BGS İnteraktif
    template: '%s — BGS İnteraktif'
  description: "🚀 20+ yıllık deneyim ile sektörlere özel mobil yazılım, donanım çözümleri, otomasyon ve Ar-Ge odaklı teknoloji projeleri geliştiriyoruz."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: BGS İnteraktif
    images:
      - url: '~/assets/images/bgs-logo.jpg'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@bgsio'
    site: '@bgsio'
    cardType: summary_large_image

i18n:
  language: tr
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'kategori'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'etiket'
      robots:
        index: false
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: G-XXXXXXXXXX

ui:
  theme: 'system' # or "light", "dark"
